apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: locust
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: locust
    repoURL: https://raw.githubusercontent.com/hansehe/locust/master/helm/charts
    targetRevision: 0.1.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true