apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodbtestone
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: community-operator
    helm:
      values:
    repoURL: https://mongodb.github.io/helm-charts
    targetRevision: 0.7.8
  syncPolicy:
    automated:
      prune: true
      selfHeal: true