apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-timo
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: charts/mongodb
    repoURL: https://github.com/TheRudin/argocd.git
    targetRevision: HEAD
    helm:
      mongodb: |
        metadata:
          name: mongodb-timo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true